SnowFlake =
{140,{1.2540383223269e-015,-20.48},{17.736200269506,-10.24},{17.736200269506,10.24},{1.2540383223269e-015,20.48},{-17.736200269506,10.24},{-17.736200269506,-10.24},{2.5080766446538e-015,-40.96},{35.47240053901,-20.48},{35.47240053901,20.48},{2.5080766446538e-015,40.96},{-35.47240053901,20.48},{-35.47240053901,-20.48},{3.7621149669806e-015,-61.44},{53.208600808516,-30.72},{53.208600808516,30.72},{3.7621149669806e-015,61.44},{-53.208600808516,30.72},{-53.208600808516,-30.72},{5.0161532893076e-015,-81.92},{70.944801078022,-40.96},{70.944801078022,40.96},{5.0161532893076e-015,81.92},{-70.944801078022,40.96},{-70.944801078022,-40.96},{6.2701916116344e-015,-102.4},{88.681001347528,-51.2},{88.681001347528,51.2},{6.2701916116344e-015,102.4},{-88.681001347528,51.2},{-88.681001347528,-51.2},{7.5242299339616e-015,-122.88},{106.41720161703,-61.44},{106.41720161703,61.44},{7.5242299339616e-015,122.88},{-106.41720161703,61.44},{-106.41720161703,-61.44},{8.778268256288e-015,-143.36},{124.15340188654,-71.68},{124.15340188654,71.68},{8.778268256288e-015,143.36},{-124.15340188654,71.68},{-124.15340188654,-71.68},{1.0032306578615e-014,-163.84},{141.88960215605,-81.92},{141.88960215605,81.92},{1.0032306578615e-014,163.84},{-141.88960215605,81.92},{-141.88960215605,-81.92},{1.1286344900942e-014,-184.32},{159.62580242555,-92.16},{159.62580242555,92.16},{1.1286344900942e-014,184.32},{-159.62580242555,92.16},{-159.62580242555,-92.16},{31.038350471634,-53.76},{46.557525707451,-44.8},{62.076700943269,-17.92},{62.076700943269,0},{62.076700943269,17.92},{46.557525707451,44.8},{31.038350471634,53.76},{15.519175235817,62.72},{4.3891341281442e-015,71.68},{-15.519175235817,62.72},{-31.038350471634,53.76},{-46.557525707451,44.8},{-62.076700943269,17.92},{-62.076700943269,7.6022033111802e-015},{-62.076700943269,-17.92},{-46.557525707451,-44.8},{-31.038350471634,-53.76},{-15.519175235817,-62.72},{-1.3167402384433e-014,-71.68},{15.519175235817,-62.72},{46.557525707451,-80.64},{62.076700943269,-71.68},{77.595876179085,-62.72},{93.115051414904,-35.84},{93.115051414904,-17.92},{93.115051414904,0},{93.115051414904,17.92},{93.115051414904,35.84},{77.595876179085,62.72},{62.076700943269,71.68},{46.557525707451,80.64},{31.038350471634,89.6},{15.519175235817,98.56},{-15.519175235817,98.56},{-31.038350471634,89.6},{-46.557525707451,80.64},{-62.076700943269,71.68},{-77.595876179085,62.72},{-93.115051414904,35.84},{-93.115051414904,17.92},{-93.115051414904,1.140330496677e-014},{-93.115051414904,-17.92},{-93.115051414904,-35.84},{-77.595876179085,-62.72},{-62.076700943269,-71.68},{-46.557525707451,-80.64},{-31.038350471634,-89.6},{-15.519175235817,-98.56},{15.519175235817,-98.56},{31.038350471634,-89.6},{15.519175235817,-142.08},{-15.519175235817,-142.08},{-115.28530175178,-84.48},{-130.8044769876,-57.6},{-130.8044769876,57.6},{-115.28530175178,84.48},{-15.519175235817,142.08},{15.519175235817,142.08},{115.28530175178,84.48},{130.8044769876,57.6},{130.8044769876,-57.6},{115.28530175178,-84.48},{31.038350471634,-151.04},{-31.038350471634,-151.04},{-115.28530175178,-102.4},{-146.32365222342,-48.64},{-146.32365222342,48.64},{-115.28530175178,102.4},{-31.038350471634,151.04},{31.038350471634,151.04},{115.28530175178,102.4},{146.32365222342,48.64},{146.32365222342,-48.64},{115.28530175178,-102.4},{46.557525707451,-160},{-46.557525707451,-160},{-115.28530175178,-120.32},{-161.84282745924,-39.68},{-161.84282745924,39.68},{-115.28530175178,120.32},{-46.557525707451,160},{46.557525707451,160},{115.28530175178,120.32},{161.84282745924,39.68},{161.84282745924,-39.68},{115.28530175178,-120.32}}

---- Calculating death variable ----
SDspeed = 1000 // 29
---- Calculating death variable ----

-- Laptop
-- __MapDirSetting("C:\\Users\\rlatj\\Desktop\\workingarea\\mapping\\MSF_U")
-- __SubDirSetting("C:\\Users\\rlatj\\Desktop\\workingarea\\mapping\\MSF_U")


-- Desktop
__MapDirSetting("C:\\Users\\USER\\Desktop\\mapping\\tesingmap")
__SubDirSetting("C:\\Users\\USER\\Desktop\\mapping\\tesingmap\\lua")


-- This text is generated by TrigEditPlus
--↓ Tep에 그대로 붙여넣기----------------------------------------
FP = P8
SetForces({P1,P2,P3,P4},{P5,P6,P7,P8},{},{},{P1,P2,P3,P4,P5,P6,P7,P8}) 
SetFixedPlayer(P6)
-- StartCtrig(1,nil,0,1,"C:\\Users\\rlatj\\Desktop\\workingarea\\mapping\\euddraft0.9.10.12")
StartCtrig(1,nil,0,1,"C:\\Users\\USER\\Desktop\\mapping\\euddraft0.9.10.12")
CJump(AllPlayers,0)
Include_DataTransfer()
Include_CBPaint()
Include_CtrigPlib(360,"Switch 254",1)
Include_64BitLibrary("Switch 255")


Nextptrs = CreateVar(FP)
CanWT = CreateCcode()
CanCT = CreateCcode()
P_Count = CreateNcode()

CJumpEnd(AllPlayers,0)
Enable_PlayerCheck()
ObserverChatToAll(FP, _Void(0xFF), nil, nil, 0)
NoAirCollisionX(FP)
DoActions(FP,{SetSpeed(SetTo, "#X5")})
function RotatePlayer(Print,Players,RecoverCP)
	return CopyCpAction(Print,Players,RecoverCP)
end
-- 여기에 변수, 배열 및 Include류 함수 선언 --

function SetMemoryBA(Offset,Type,Value)
	local ret = bit32.band(Offset, 0xFFFFFFFF)%4
	if ret == 0 then
		Mask = 0xFF
	elseif ret == 1 then
		Mask = 0xFF00
		Value = Value * 0x100
	elseif ret == 2 then
		Mask = 0xFF0000
		Value = Value * 0x10000
	elseif ret == 3 then
		Mask = 0xFF000000
		Value = Value * 0x1000000
	end
	return SetMemoryX(Offset-ret,Type,Value,Mask)
end

function StrDesignX(Str)
	return "\x13\x07。\x18˙\x0F+\x1C˚ "..Str.." \x1C。\x0F+\x18.\x07˚"
end

function AddV(V,Value)
	if Value == nil then Value = 1 end
	if FP == nil then PushErrorMsg("FP Player not defined") end
	if type(Value) == "number" then
		return SetCVar(FP,V[2],Add,Value)
	else
		return TSetCVar(FP,V[2],Add,Value)
	end
end

JYD = "Set Unit Order To: Junk Yard Dog"
Gentime = SDspeed * 251

---------------------- Init system setting --------
Trigger {
    players = {Force1},
    conditions = {
        Deaths(CurrentPlayer,Exactly,0,158);
        Bring(CurrentPlayer,AtLeast,1,12,"mainLocation")
    },
    actions = {
        RemoveUnitAt(1,12,"mainLocation",CurrentPlayer);
        DisplayText("브금ㄴㄴ");
        SetDeaths(CurrentPlayer,SetTo,1,158);
        PreserveTrigger()
    },
}

Trigger { -- off
    players = {Force1},
    conditions = {
        Deaths(CurrentPlayer,Exactly,1,158);
        Bring(CurrentPlayer,AtLeast,1,12,"mainLocation")
    },
    actions = {
        RemoveUnitAt(1,12,"mainLocation",CurrentPlayer);
        DisplayText("브금ㅇㅇ");
        SetDeaths(CurrentPlayer,SetTo,0,158);
        PreserveTrigger()
    },
}


for i=0, 3 do -- 예약메딕

    Trigger { -- 
        players = {i},
        conditions = {
            Always()
        },
        actions = {
            SetMemoryBA(0x57F27C+(228*i)+2,SetTo,0);
            SetMemoryBA(0x57F27C+(228*i)+34,SetTo,1);
        },
    }
    
    Trigger { -- 
        players = {i},
        conditions = {
            Deaths(i,Exactly,0,"Map Revealer");
            Bring(i,AtLeast,1,17,"Anywhere");
        },
        actions = {
            RemoveUnit(17,i);
            DisplayText("2Tic 예약메딕 사용 200 Ore.");
            SetMemoryBA(0x57F27C+(228*i)+2,SetTo,1);
            SetMemoryBA(0x57F27C+(228*i)+34,SetTo,0);
            SetDeaths(i,SetTo,1,"Map Revealer");
            PreserveTrigger();
        },
    }
    
    Trigger { -- 
        players = {i},
        conditions = {
            Deaths(i,Exactly,1,"Map Revealer");
            Bring(i,AtLeast,1,17,"Anywhere");
        },
        actions = {
            RemoveUnit(17,i);
            DisplayText("예약메딕 사용안함 150 Ore.");
            SetMemoryBA(0x57F27C+(228*i)+2,SetTo,0);
            SetMemoryBA(0x57F27C+(228*i)+34,SetTo,1);
            SetDeaths(i,SetTo,0,"Map Revealer");
            PreserveTrigger();
        },
    }
    
    end
    Trigger { -- 1틱메딕
        players = {Force1},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, "Terran Medic");
        },
        actions = {
            ModifyUnitHitPoints(All, "Men", CurrentPlayer, "Anywhere", 100);
            ModifyUnitShields(All, "Men", CurrentPlayer, "Anywhere", 100);
            RemoveUnit("Terran Medic", CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    Trigger { -- 2틱메딕
        players = {Force1},
        conditions = {
            Command(CurrentPlayer, AtLeast, 1, 2);
        },
        actions = {
            ModifyUnitHitPoints(All, "Men", CurrentPlayer, "Anywhere", 100);
            ModifyUnitShields(All, "Men", CurrentPlayer, "Anywhere", 100);
            RemoveUnit(2, CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    
    Trigger { -- 일마 생산
        players = {AllPlayers},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, 0, "mainLocation");
        },
        actions = {
            PlayWAV("staredit\\wav\\ghost_dead.ogg");
            CreateUnit(1, 0, "HealZone", CurrentPlayer);
            RemoveUnitAt(1, 0, "mainLocation", CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    Trigger { -- 영마 생산
        players = {AllPlayers},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, 20, "mainLocation");
        },
        actions = {
            PlayWAV("staredit\\wav\\ghost_living.ogg");
            RemoveUnitAt(1, 20, "mainLocation", CurrentPlayer);
            CreateUnit(1, 20, "HealZone", CurrentPlayer);
            PreserveTrigger();
        },
    }
    
    Trigger { -- 스마 생산
        players = {AllPlayers},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, 1, "mainLocation");
        },
        actions = {
            PlayWAV("staredit\\wav\\ghost_nevergiveup.ogg");
            RemoveUnitAt(1, 1, "mainLocation", CurrentPlayer);
            CreateUnit(1, 1, "HealZone", CurrentPlayer);
            PreserveTrigger();
        },
    }

----------- Special building trigger

TriggerX(P7, Always(), {Wait(100),CreateUnit(1, 151, "celebrate1", P7),CreateUnit(1, 151, "celebrate2", P7)})

---------- Exchange Trigger

ExRate = {29,31,33,35}

for i = 0, 3 do
	TriggerX(P8,{Command(Force1,Exactly,i+1,111)},{SetNDeaths(FP,SetTo,i+1,P_Count)},{Preserved}) -- 상시 플레이어수 체크
end


for i = 0, 3 do
    for j = 15, 0, -1 do
    Trigger {
            players = {Force1},
            conditions = {
                    Label(0);
                    Score(CurrentPlayer,Kills,AtLeast,2^j*100); 
                    NDeaths(FP,Exactly,i+1,P_Count); 
                },
            actions = {
                    SetScore(CurrentPlayer,Subtract,2^j*100,Kills);
                    SetResources(CurrentPlayer,Add,2^j*ExRate[i+1],Ore);
                    PreserveTrigger()
                    }
    }
    end 
    end


-- for j = 15, 0, -1 do
--         TriggerX(Force1,{Score(CurrentPlayer,Kills,AtLeast,2^j*100)},{
--             SetScore(CurrentPlayer,Subtract,2^j*100,Kills);
--             SetResources(CurrentPlayer,Add,2^j*ExRate[i],Ore);
--         },{Preserved})
-- end
    -------------------------- Wave Trigger ------------------------------

    WAVE1 = CSMakePolygon(4,50,0,35,5)
    WAVE2 = CSMakePolygon(4,50,0,20,5)
    WAVE3 = CSMakePolygon(4,50,45,13,5)
    
    ----------- 30 sec period --------
    
    Trigger{
        players = {P6},
        conditions = {
            Always();
        },
        actions = {
            SetDeaths(P8, Add, 1, 131);
            PreserveTrigger();
        }
    }
    
    Trigger2(P6, {Deaths(P8, Exactly, 1020, 131)}, SetDeaths(P8, SetTo, 0, 131),{preserved})
    
    
    CSPlotOrder(WAVE1, P7, 40, "celebrate1", nil, 1, 32, CSMakePolygon(4,1,0,35,5), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, 1019, 131)},nil,1)
    CSPlotOrder(WAVE2, P7, 44, "celebrate1", nil, 1, 32, CSMakePolygon(4,1,0,20,5), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, 1019, 131)},nil,1)
    CSPlotOrder(WAVE3, P7, 51, "celebrate1", nil, 1, 32, CSMakePolygon(4,1,45,13,5), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, 1019, 131)},nil,1)

    CSPlotOrder(WAVE1, P7, 40, "celebrate2", nil, 1, 32, CSMakePolygon(4,1,0,35,5), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, 1019, 131)},nil,1)
    CSPlotOrder(WAVE2, P7, 44, "celebrate2", nil, 1, 32, CSMakePolygon(4,1,0,20,5), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, 1019, 131)},nil,1)
    CSPlotOrder(WAVE3, P7, 51, "celebrate2", nil, 1, 32, CSMakePolygon(4,1,45,13,5), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, 1019, 131)},nil,1)

------------------ Big Wave Trigger 132 -----------------

Bigwave1 = CSMakePolygon(6,45,0,50,1)
Bigwave2 = CSMakeLine(6,80,0,15,0)

Trigger{
	players = {P6},
	conditions = {
		Always();
	},
	actions = {
		SetDeaths(P8, Add, 1, 132);
		PreserveTrigger()
	}
}

for i = 1 , 10 do
	Trigger2(Force1, Deaths(P8, Exactly, Gentime * i, 132), {PlayWAV("staredit\\wav\\bigwave.ogg"),PlayWAV("staredit\\wav\\bigwave.ogg"),PlayWAV("staredit\\wav\\bigwave.ogg"),MinimapPing("celebrate1")})
	CSPlotOrder(Bigwave1, P6, 54, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 53, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 55, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 56, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave2, P6, 62, "celebrate1", nil, 1, 32, CSMakeLine(6,1,0,15,0), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
end

for i = 10, 15 do
	Trigger2(Force1, Deaths(P8, Exactly, Gentime * i + 120, 132), {PlayWAV("staredit\\wav\\bigwave.ogg"),PlayWAV("staredit\\wav\\bigwave.ogg"),PlayWAV("staredit\\wav\\bigwave.ogg"),MinimapPing("celebrate1")})
	CSPlotOrder(Bigwave1, P6, 65, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 66, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 51, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 88, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave2, P6, 70, "celebrate1", nil, 1, 32, CSMakeLine(6,1,0,15,0), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
end

for i = 16, 20 do
	Trigger2(Force1, Deaths(P8, Exactly, Gentime * i + 180, 132), {PlayWAV("staredit\\wav\\bigwave.ogg"),PlayWAV("staredit\\wav\\bigwave.ogg"),PlayWAV("staredit\\wav\\bigwave.ogg"),MinimapPing("celebrate1")})
	CSPlotOrder(Bigwave1, P6, 77, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 78, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 104, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 88, "celebrate1", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave2, P6, 64, "celebrate1", nil, 1, 32, CSMakeLine(6,1,0,15,0), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
end


for i = 1 , 10 do
	Trigger2(Force1, Deaths(P8, Exactly, Gentime * i, 132), {MinimapPing("celebrate2")})
	CSPlotOrder(Bigwave1, P6, 54, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 53, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 55, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 56, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
	CSPlotOrder(Bigwave2, P6, 62, "celebrate2", nil, 1, 32, CSMakeLine(6,1,0,15,0), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i, 132)},nil,1)
end

for i = 10, 15 do
	Trigger2(Force1, Deaths(P8, Exactly, Gentime * i + 120, 132), {MinimapPing("celebrate2")})
	CSPlotOrder(Bigwave1, P6, 65, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 66, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 51, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 88, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
	CSPlotOrder(Bigwave2, P6, 70, "celebrate2", nil, 1, 32, CSMakeLine(6,1,0,15,0), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 120, 132)},nil,1)
end

for i = 16, 20 do
	Trigger2(Force1, Deaths(P8, Exactly, Gentime * i + 180, 132), {MinimapPing("celebrate2")})
	CSPlotOrder(Bigwave1, P6, 77, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 78, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 104, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave1, P6, 88, "celebrate2", nil, 1, 32, CSMakePolygon(6,1,0,50,1), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
	CSPlotOrder(Bigwave2, P6, 64, "celebrate2", nil, 1, 32, CSMakeLine(6,1,0,15,0), 0, Attack, "HealZone", nil, 64, nil, P6,{Deaths(P8, Exactly, Gentime * i + 180, 132)},nil,1)
end

    
    ----------- Heal Zone -----------
    TriggerX(FP, Always(), ModifyUnitShields(All, "Any unit", AllPlayers, "Anywhere", 100));
    TriggerX(FP, Always(), ModifyUnitHitPoints(All, "Any unit", AllPlayers, "Anywhere", 100));
    Trigger {
        players = {Force1},
        conditions = {
            Deaths(CurrentPlayer, AtLeast, 100, "Young Chrysalis");
        },
        actions = {
            SetDeaths(CurrentPlayer, SetTo, 0, "Young Chrysalis");
            ModifyUnitHitPoints(All, "Men", CurrentPlayer, "HealZone", 100);
            ModifyUnitShields(All, "Men", CurrentPlayer, "HealZone", 100);
            PreserveTrigger();
        },
    }
    
    
    Trigger {
        players = {Force1},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, "Any unit", "HealZone");
        },
        actions = {
            SetDeaths(CurrentPlayer, Add, 1, "Young Chrysalis");
            PreserveTrigger();
        },
    }
------------- 영작 트리거


Trigger { -- 영작유닛 데스값 -1
	players = {P7},
	conditions = {
		Always();
	},
	actions = {
		SetDeaths(CurrentPlayer, Subtract, 1, 77);
		SetDeaths(CurrentPlayer, Subtract, 1, 78);
		SetDeaths(CurrentPlayer, Subtract, 1, 52);
		SetDeaths(CurrentPlayer, Subtract, 1, 104);
		SetDeaths(CurrentPlayer, Subtract, 1, 70);
		SetDeaths(CurrentPlayer, Subtract, 1, 21);
		SetDeaths(CurrentPlayer, Subtract, 1, 23);
		SetDeaths(CurrentPlayer, Subtract, 1, 93);
		SetDeaths(CurrentPlayer, Subtract, 1, 69);
		SetDeaths(CurrentPlayer, Subtract, 1, 28);
		SetDeaths(CurrentPlayer, Subtract, 1, 62);
		SetDeaths(CurrentPlayer, Subtract, 1, 86);
		SetDeaths(CurrentPlayer, Subtract, 1, 27);
		SetDeaths(CurrentPlayer, Subtract, 1, 64);
		SetDeaths(CurrentPlayer, Subtract, 1, 7);
		SetDeaths(CurrentPlayer, Subtract, 1, 3);
		SetDeaths(CurrentPlayer, Subtract, 1, 60);
		SetDeaths(CurrentPlayer, Subtract, 1, 58);
		SetDeaths(CurrentPlayer, Subtract, 1, 76);
		SetDeaths(CurrentPlayer, Subtract, 1, 75);
		SetDeaths(CurrentPlayer, Subtract, 1, 74);

		PreserveTrigger();
	},
}


Trigger{
	players = {force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 150);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Gift \x03box \x11ﾟ.+｡ \x04를 열어 \x1970000 \x1FPoint\x04를 획득했습니다 !", 4);
		SetScore(CurrentPlayer, Add, 70000, Kills);
		PlayWAV("staredit\\wav\\hey.ogg");
		PlayWAV("staredit\\wav\\hey.ogg");
		PlayWAV("staredit\\wav\\hey.ogg");
		PlayWAV("staredit\\wav\\hey.ogg");
		PlayWAV("staredit\\wav\\hey.ogg");
		PlayWAV("staredit\\wav\\hey.ogg");
		PreserveTrigger();
	}
}

Trigger{
	players = {P6},
	conditions = {
		Always();
	},
	actions = {
		SetDeaths(P7, Subtract, 1, 150);
		PreserveTrigger();
	}
}

Trigger { -- fenix z
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 77);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Didymos \x11ﾟ.+｡ \x01을 \x06처치 \x04하였습니다 + 35000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 35000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- fenix d
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 78);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Dimorphos \x11ﾟ.+｡ \x01을 \x06처치 \x04하였습니다 + 40000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 40000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- unclean
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 52);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Biela’s Comet \x11ﾟ.+｡ \x01을 \x06처치 \x04하였습니다 + 45000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 45000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- inf duran
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 104);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Psyche \x11.+ﾟ｡ \x01을 \x06처치 \x04하였습니다 + 45000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 45000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- scout
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 70);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Restriction \x11.+ﾟ｡ \x01을 \x06처치 \x04하였습니다 + 50000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 50000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- No comment (ABB625F6)
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 21);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Aphophis \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 55000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 55000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- tank
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 23);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Comet Hyakutake \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 100000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 100000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- scantid
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 93);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03'Oumuamua \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 45000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 45000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- matriach
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 69);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Vesta \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 50000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 50000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- yamabattle
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 28);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Cassini \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 130000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 130000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- devour H
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 62);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Bennu \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 65000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 65000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- Danimoth
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 86);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Borisov \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 85000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 85000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- Goliath
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 3);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Perseid meteor \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 75000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 75000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- Nuke battle
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 27);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Tempel 1 \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 200000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 200000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- Prove
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 64);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Halley’s Comet \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 70000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 70000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger { -- SCV
	players = {Force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 7);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Pluto \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 75000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 75000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	},
}

Trigger{ -- Corsair
	players = {force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 60);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Ikeya-Seki \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 90000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 90000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	}
}

Trigger{ -- Intercepter
	players = {force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 58);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Intercepter \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 80000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 80000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	}
}

Trigger{ -- DA
	players = {force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 76);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Purity \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 85000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 85000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	}
}

Trigger{ -- ZE
	players = {force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 75);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Veil \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 100000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 100000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	}
}

Trigger{ -- HD
	players = {force1},
	conditions = {
		Deaths(P7, AtLeast, 1, 74);
		Deaths(P9,Exactly,0,200)
	},
	actions = {
		DisplayText("\x13\x11｡˙+ﾟ\x08Parallel's \x03Unrevealer \x11.+ﾟ｡ \x01를 \x06처치 \x04하였습니다 + 150000 \x1FPoints!\x04", 4);
		SetScore(CurrentPlayer, Add, 150000, Kills);
		PlayWAV("staredit\\wav\\killsound.wav");
		PlayWAV("staredit\\wav\\killsound.wav");
		PreserveTrigger();
	}
}








    ------------ Bunker Heal Zone ----------
    Trigger{
        players = {Force1},
        conditions = {
            Bring(CurrentPlayer, AtLeast, 1, 125, "HealZone");
            },
        actions = {
            SetDeaths(P8, Add, 1, 176);
            PreserveTrigger();
        },
    }
    
    
    Trigger{
        players = {Force1},
        conditions = {
            Deaths(P8, AtLeast, 1, 176);
        },
        actions = {
            SetDeaths(P8, SetTo, 0, 176);
            ModifyUnitHitPoints("Buildings", 125, CurrentPlayer, "HealZone", 100);
            ModifyUnitHitPoints("Buildings", 125, P12, "HealZone", 100);
            ModifyUnitShields("Buildings", 125, CurrentPlayer, "HealZone", 100);
            PreserveTrigger();
        },
    }
------ Neutral bunker trigger ------
for i = 0, 3 do
    Trigger2(Force1, {Bring(CurrentPlayer,AtLeast,1,"Men","neutralbunker"..(i+1)),Bring(P12,AtLeast,1,125,"neutralbunker"..(i+1))}, 
    {GiveUnits(All,125,P12,"neutralbunker"..(i+1),CurrentPlayer),
    SetInvincibility(Disable, 125, CurrentPlayer, "neutralbunker"..(i+1))
},preserved)
end

for i = 0, 3 do
    Trigger2(Force1, {Bring(CurrentPlayer,Exactly,0,"Men","neutralbunker"..(i+1)),Bring(CurrentPlayer,AtLeast,1,125,"neutralbunker"..(i+1))},
    { 
        GiveUnits(All,125,CurrentPlayer,"neutralbunker"..(i+1),P12),
        SetInvincibility(Enable, 125, P12, "neutralbunker"..(i+1))
    },preserved)
end

    ------<  기부 트리거  >--------------------------------------------- [ GiveRateUnit = 8  ]
    GText1 = "\x13\x1F─━┫ \x04기부금액 단위가 \x1F5,000 Ore \x04로 \x11변경\x04되었습니다. \x1F┣━─"
    GText2 = "\x13\x1F─━┫ \x04기부금액 단위가 \x1F10,000 Ore \x04로 \x11변경\x04되었습니다. \x1F┣━─"
    GText3 = "\x13\x1F─━┫ \x04기부금액 단위가 \x1F50,000 Ore \x04로 \x11변경\x04되었습니다. \x1F┣━─"
    GText4 = "\x13\x1F─━┫ \x04기부금액 단위가 \x1F100,000 Ore \x04로 \x11변경\x04되었습니다. \x1F┣━─"
    GText5 = "\x13\x1F─━┫ \x04기부금액 단위가 \x1F500,000 Ore \x04로 \x11변경\x04되었습니다. \x1F┣━─"
    GText6 = "\x13\x1F─━┫ \x04기부금액 단위가 \x1F1,000 Ore \x04로 \x11변경\x04되었습니다. \x1F┣━─"
    -- 1000 = 0 // 5000 = 1 // 10000 = 2 // 50000 = 3 // 100000 = 4 // 500000 = 5
    GTable = {{0,1,GText1},{1,2,GText2},{2,3,GText3},{3,4,GText4},{4,5,GText5},{5,0,GText6}}
    --Give Trig -- [ GiveUnit (58,60,69,71,72) ]
    --GiveRate 0~5 [ 5000, 10000, 50000, 100000, 500000, 1000 ]
    
    GiveRate = CreateNcode()
    
    GiveRate2 = {1000,5000,10000,50000,100000,500000}
    GiveUnitID = {58,60,69,71,72}
    PlayerArr = {"\x08P1","\x0EP2","\x0FP3","\x10P4","\x11P5"}
    
    CIf(Force1,{Bring(CurrentPlayer,AtLeast,1,11,"Anywhere")})
    
    for i = 0, 3 do
    for j = 1, 6 do
    Trigger {
        players = {i},
        conditions = {
                Label(0);
                NDeaths(i,Exactly,GTable[j][1],GiveRate);
                Bring(CurrentPlayer,AtLeast,1,11,"Anywhere")
            },
        actions = {
                GiveUnits(all,11,i,"Anywhere",P12);
                ModifyUnitEnergy(all, 11, P12, "Anywhere", 0);
                RemoveUnit(11,P12);
                DisplayText(GTable[j][3],4);
                SetNDeaths(i,SetTo,GTable[j][2],GiveRate);
                PreserveTrigger();
            }
    }
    
    end end
    
    CIfEnd()
    
    for k = 0, 3 do
    for j = 0, 3 do
    if k~=j then
    CIf(k,Bring(k,AtLeast,1,GiveUnitID[j+1],"Anywhere"))
        for i = 0, 5 do
        Trigger {
                players = {k},
                conditions = {
                        Label(0);
                        Bring(k,AtLeast,1,GiveUnitID[j+1],"Anywhere");
                        PlayerCheck(j,1);
                        NDeaths(k,Exactly,i,GiveRate);
                        Accumulate(k,AtMost,GiveRate2[i+1],Ore);
                    },
                actions = {
                        ModifyUnitEnergy(all, GiveUnitID[j+1], k, "Anywhere", 0);
                        RemoveUnitAt(1,GiveUnitID[j+1],"Anywhere",k);
                        DisplayText("\x1F─━┫ “ \x1F잔액\x04이 부족합니다.\x0F”",4);
                        PreserveTrigger()
                    },
            }
        Trigger {
                players = {k},
                conditions = {
                        Label(0);
                        Bring(k,AtLeast,1,GiveUnitID[j+1],"Anywhere");
                        PlayerCheck(j,1);
                        NDeaths(k,Exactly,i,GiveRate);
                        Accumulate(k,AtLeast,GiveRate2[i+1],Ore);
                        Accumulate(k,AtMost,0x7FFFFFFF,Ore);
                    },
                actions = {
                        SetResources(k,Subtract,GiveRate2[i+1],Ore);
                        SetResources(j,Add,GiveRate2[i+1],Ore);
                        ModifyUnitEnergy(all, GiveUnitID[j+1], k, "Anywhere", 0);
                        RemoveUnitAt(1,GiveUnitID[j+1],"Anywhere",k);
                        DisplayText("\x1F─━┫ “ "..PlayerArr[j+1].."\x04에게 \x1F"..GiveRate2[i+1].." Ore\x04를 기부하였습니다. \x0F”",4);
                        SetMemory(0x6509B0,SetTo,j);
                        DisplayText("\x1F─━┫ “ "..PlayerArr[k+1].."\x04에게 \x1F"..GiveRate2[i+1].." Ore\x04를 기부받았습니다. \x0F”",4);
                        SetMemory(0x6509B0,SetTo,k);
                        PreserveTrigger();
                    },
            }
        end
    Trigger {
        players = {k},
        conditions = {
                Label(0);
                Bring(k,AtLeast,1,GiveUnitID[j+1],"Anywhere");
                PlayerCheck(j,0);
            },
        actions = {
                DisplayText("\x1F─━┫ “"..PlayerArr[j+1].."\x04이(가) 존재하지 않습니다. \x0F”",4);
                ModifyUnitEnergy(all, GiveUnitID[j+1], k, "Anywhere", 0);
                RemoveUnitAt(1,GiveUnitID[j+1],"Anywhere",k);
                PreserveTrigger();
                    },
            }
        
    CIfEnd()
    elseif k==j then
        TriggerX(k,{Bring(k,AtLeast,1,GiveUnitID[j+1],"Anywhere")},{
            ModifyUnitEnergy(all, GiveUnitID[j+1], k, "Anywhere", 0);
            RemoveUnitAt(1,GiveUnitID[j+1],"Anywhere",k);
        },{Preserved})
    end end end
    
--------------------- Ban Trigger ------------------------

BanText = "\x13\x1F─━┫【 \x04당신은 \x11방장에 의해 \x08강제퇴장 \x04당하였습니다.  \x1F】┣━─"
BanLocArr = {"banP1","banP2","banP3","banP4"}
for i = 0, 3 do
Trigger {
    players = {FP},
    conditions = {
            Label(0);
            Bring(Force1,AtLeast,1,15,BanLocArr[i+1]);
        },
    actions = {
            RotatePlayer({DisplayTextX(BanText)},{i},FP);
            RotatePlayer({Defeat()},{i},FP);
        }
}
end
    
for e = 1, 2 do    
    for i = 0, 3 do    
        Trigger { -- 일마  > 영마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 0, "convertH"..e);
                Accumulate(CurrentPlayer, AtLeast, 10000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 10000, Ore);
                RemoveUnitAt(1, 0, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 20, "HealZone", CurrentPlayer);
                DisplayText("Convert Hero Text", 4);
                PlayWAV("staredit\\wav\\ghost_living.ogg");
                PreserveTrigger();
            },
        }
        
        Trigger { -- 영마 > 스마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 20, "convertH"..e);
                Bring(CurrentPlayer, AtLeast, 1, 129, "Anywhere");
                Accumulate(CurrentPlayer, AtLeast, 15000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 15000, Ore);
                RemoveUnitAt(1, 20, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 1, "HealZone", CurrentPlayer);
                DisplayText("Convert Special Text", 4);
                PlayWAV("staredit\\wav\\ghost_nevergiveup.ogg");
                PreserveTrigger();
            },
        }
        
        Trigger { -- 일마  > 영마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 0, "convertH"..e);
                Accumulate(CurrentPlayer, AtLeast, 10000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 10000, Ore);
                RemoveUnitAt(1, 0, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 20, "HealZone", CurrentPlayer);
                DisplayText("Convert Hero Text", 4);
                PlayWAV("staredit\\wav\\ghost_dead.ogg");
                PreserveTrigger();
            },
        }
        
        Trigger { -- 영마 > 스마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 20, "convertH"..e);
                Bring(CurrentPlayer, AtLeast, 1, 129, "Anywhere");
                Accumulate(CurrentPlayer, AtLeast, 15000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 15000, Ore);
                RemoveUnitAt(1, 20, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 1, "HealZone", CurrentPlayer);
                DisplayText("Convert Special Text", 4);
                PlayWAV("staredit\\wav\\ghost_living.ogg");
                PreserveTrigger();
            },
        }
        
        Trigger { -- 일마  > 영마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 0, "convertH"..e);
                Accumulate(CurrentPlayer, AtLeast, 10000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 10000, Ore);
                RemoveUnitAt(1, 0, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 20, "HealZone", CurrentPlayer);
                DisplayText("Convert Hero Text", 4);
                PlayWAV("staredit\\wav\\ghost_dead.ogg");
                PreserveTrigger();
            },
        }
        
        Trigger { -- 영마 > 스마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 20, "convertH"..e);
                Bring(CurrentPlayer, AtLeast, 1, 129, "Anywhere");
                Accumulate(CurrentPlayer, AtLeast, 15000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 15000, Ore);
                RemoveUnitAt(1, 20, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 1, "HealZone", CurrentPlayer);
                DisplayText("Convert Special Text", 4);
                PlayWAV("staredit\\wav\\ghost_living.ogg");
                PreserveTrigger();
            },
        }
        
        Trigger { -- 일마  > 영마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 0, "convertH"..e);
                Accumulate(CurrentPlayer, AtLeast, 10000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 10000, Ore);
                RemoveUnitAt(1, 0, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 20, "HealZone", CurrentPlayer);
                DisplayText("Convert Hero Text", 4);
                PlayWAV("staredit\\wav\\ghost_dead.ogg");
                PreserveTrigger();
            },
        }

        Trigger { -- 일마  > 영마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 0, "convertH"..e);
                Accumulate(CurrentPlayer, AtLeast, 10000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 10000, Ore);
                RemoveUnitAt(1, 0, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 20, "HealZone", CurrentPlayer);
                DisplayText("Convert Hero Text", 4);
                PlayWAV("staredit\\wav\\ghost_dead.ogg");
                PreserveTrigger();
            },
        }

        
        Trigger { -- 영마 > 스마 변환
            players = {CurrentPlayer},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 20, "convertH"..e);
                Bring(CurrentPlayer, AtLeast, 1, 129, "Anywhere");
                Accumulate(CurrentPlayer, AtLeast, 15000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 15000, Ore);
                RemoveUnitAt(1, 20, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 1, "HealZone", CurrentPlayer);
                DisplayText("Convert Special Text", 4);
                PlayWAV("staredit\\wav\\ghost_living.ogg");
                PreserveTrigger();
            },
        }

        Trigger { -- 영마 > 스마 변환
            players = {i},
            conditions = {
                Bring(CurrentPlayer, AtLeast, 1, 20, "convertH"..e);
                Bring(CurrentPlayer, AtLeast, 1, 129, "Anywhere");
                Accumulate(CurrentPlayer, AtLeast, 15000, Ore);
            },
            actions = {
                SetResources(CurrentPlayer, Subtract, 15000, Ore);
                RemoveUnitAt(1, 20, "convertH"..e, CurrentPlayer);
                CreateUnit(1, 1, "HealZone", CurrentPlayer);
                DisplayText("Convert Special Text", 4);
                PlayWAV("staredit\\wav\\ghost_living.ogg");
                PreserveTrigger();
            },
        }
        
    end
end
    Trigger{
        players = {Force1},
        conditions = {
            Deaths(P7, Exactly, 1, 152);
            Deaths(P9,Exactly,0,200);
        },
        actions = {
            DisplayText("\x13\x19｡˙+ﾟ\x11Special \x1fGuardians of \x19Galaxy\x19 ｡+ﾟ. 가 전장에 합류했습니다 !", 4);
            PlayWAV("staredit\\wav\\unlock.ogg");
            PlayWAV("staredit\\wav\\unlock.ogg");
            PlayWAV("staredit\\wav\\unlock.ogg");
        }
    }
    
    
    
    Trigger{ -- 해금
        players = {P1},
        conditions = {
            Deaths(P7, Exactly, 1, 152);
        },
        actions = {
            CreateUnit(1, 129, "unlock1", CurrentPlayer);
        }
    }
    
    Trigger{ -- 해금
        players = {P2},
        conditions = {
            Deaths(P7, Exactly, 1, 152);
        },
        actions = {
            CreateUnit(1, 129, "unlock2", CurrentPlayer);
        }
    }
    
    Trigger{ -- 해금
        players = {P3},
        conditions = {
            Deaths(P7, Exactly, 1, 152);
        },
        actions = {
            CreateUnit(1, 129, "unlock3", CurrentPlayer);
        }
    }
    
    Trigger{ -- 해금
        players = {P4},
        conditions = {
            Deaths(P7, Exactly, 1, 152);
        },
        actions = {
            CreateUnit(1, 129, "unlock4", CurrentPlayer);
        }
    }
    
    -------------- CPU AI Script
    -- Trigger { -- No comment (866B4FC4)
    --     players = {P6},
    --     conditions = {
    --         Always();
    --     },
    --     actions = {
    --         RunAIScriptAt("Expansion Zerg Campaign Insane", "Hive3");
    --         RunAIScriptAt("Value This Area Higher", "HealZone");
    --     },
    -- }

    
Trigger { -- 나간플레이어 유닛삭제
players = {P8},
conditions = {
        Always();
    },
actions = {
        RemoveUnit("Men",P12);
        RemoveUnit(111,P12);
        RemoveUnit(107,P12);
        PreserveTrigger();
    },
}

Trigger {
players = {Force1},
conditions = {
    Always();
},
actions = {
    SetAllianceStatus(Force1,AlliedVictory);
    SetResources(P1, Add, 1000000, Ore);
    -- PreserveTrigger();
},
}

Trigger { -- 컴퓨터동맹설정
players = {Force2},
conditions = {
    Always();
},
actions = {
    SetResources(P5, SetTo, 9999999, OreAndGas);
    SetResources(P6, SetTo, 9999999, OreAndGas);
    SetResources(P7, SetTo, 9999999, OreAndGas);
    PreserveTrigger();
    SetAllianceStatus(Force2,AlliedVictory);
    SetAllianceStatus(Force1, Enemy);
    },
}

Trigger { 
players = {Force2},
conditions = {
    Always();
},
actions = {
    RunAIScript('Turn ON Shared Vision for Player 1');
    RunAIScript('Turn ON Shared Vision for Player 2');
    RunAIScript('Turn ON Shared Vision for Player 3');
    RunAIScript('Turn ON Shared Vision for Player 4');
    PreserveTrigger();
},
}

Trigger {
players = {Force1},
conditions = {
    Always();
},
actions = {
    RunAIScript("Turn ON Shared Vision for Player 8");
    PreserveTrigger();
},
}

Trigger {
players = {Force1},
conditions = {
    Always();
},
actions = {
    RunAIScript('Turn ON Shared Vision for Player 1');
    RunAIScript('Turn ON Shared Vision for Player 2');
    RunAIScript('Turn ON Shared Vision for Player 3');
    RunAIScript('Turn ON Shared Vision for Player 4');
    PreserveTrigger();
},
}
















EndCtrig()
ErrorCheck()
EUDTurbo(FP)
-- 에러 체크 함수 선언 위치 --
--↑Tep에 그대로 붙여넣기-----



-- for i = 0, 10 do
-- if i%2 == 0 then
-- Trigger {
-- 	players = {P1},
-- 	conditions = {
-- 		Memory(0x640B60+0xDA*i, Exactly, 0xEABDB2EA);
-- 		Memory(0x640B64+0xDA*i, Exactly, 0x203AA0B3);	
-- 	},
-- 	actions = {
-- 		SetMemory(0x640B60+0xDA*i,SetTo,0);
-- 		PreserveTrigger();
-- 	}
-- }
-- Trigger {
-- 	players = {P1},
-- 	conditions = {
-- 		Memory(0x640B60+0xDA*i, Exactly, 0x4E524157);
-- 		Memory(0x640B64+0xDA*i, Exactly, 0x3A474E49);	
-- 	},
-- 	actions = {
-- 		SetMemory(0x640B60+0xDA*i,SetTo,0);
-- 		PreserveTrigger();
-- 	}
-- }
-- else
-- Trigger {
-- 	players = {P1},
-- 	conditions = {
-- 		MemoryX(0x640B5E + 0xDA*i, Exactly, 0xB2EA0000,0xFFFF0000);
-- 		Memory(0x640B62 + 0xDA*i, Exactly, 0xA0B3EABD);	
-- 		MemoryX(0x640B66 + 0xDA*i, Exactly, 0x203A,0xFFFF);
-- 	},
-- 	actions = {
-- 		SetMemory(0x640B5E + 0xDA*i,SetTo,0);
-- 		PreserveTrigger();
-- 	}
-- }
-- Trigger {
-- 	players = {P1},
-- 	conditions = {
-- 		MemoryX(0x640B5E + 0xDA*i, Exactly, 0x41570000,0xFFFF0000);
-- 		Memory(0x640B62 + 0xDA*i, Exactly, 0x4E494E52);	
-- 		MemoryX(0x640B66 + 0xDA*i, Exactly, 0x00003A47,0xFFFF);
-- 	},
-- 	actions = {
-- 		SetMemory(0x640B5E + 0xDA*i,SetTo,0);
-- 		PreserveTrigger();
-- 	}
-- }
-- end
-- end

--[[
1. Compile 후 시나리오 손상은 특정 trigger의 문제일 가능성이 농후하다.
TEP3.0 기반 트리거 자체가 트리거 용량을 많이 잡아먹어서 어쩔수없는문제. Freeze를 끄면 어느정도 해결이 된다고 함. Mininii님 피셜 

2. 중벙 트리거 관련. 중벙 안에 있는 유닛은 Men 감지를 받아서 안에있는데 갑자기 P12로 뺏기거나 하는일은 절대없음

3. 이펙트쓰다가 데스값때문에 스캔 이미지값 꼬일수있으니 웬만하면 그냥 보스페이즈 아니면 드래그방지 플래그 걸고 유닛으로 이펙트 내는게 좋다고함.



]]
